import { mkdirSync, writeFileSync, copyFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { resolve, dirname } from 'node:path';
import { getModel, listModels } from '../src/model-registry.js';
import { officialBooklet, officialPdfPage } from '../src/official-source.js';
import { checkPreviewPng } from './check-preview.mjs';
const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const output = resolve(root, 'public');
mkdirSync(output, { recursive: true });
const escape = value => String(value).replace(/[&<>"']/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[c]));
const portableExport = contents => contents.replace(/\b(href|src)="\/(?!\/)/g, '$1="./');
const styles = `body{font:14px/1.6 system-ui,sans-serif;color:#29382e;background:#faf9f4;margin:0 auto;padding:36px 24px;max-width:1000px}h1{font:38px Georgia,serif;margin:12px 0}h2{font:26px Georgia,serif;margin-top:36px}a{color:#2c5141}table{width:100%;border-collapse:collapse;background:white;font-size:13px}th,td{padding:10px;border-bottom:1px solid #e3e5dc;text-align:left}th{background:#eef2e6}td:last-child{text-align:right;font-variant-numeric:tabular-nums}img{width:90px;height:66px;object-fit:contain}small{color:#6c7b61}.summary{display:flex;gap:24px;flex-wrap:wrap;border-top:1px solid #dce2d3;border-bottom:1px solid #dce2d3;padding:18px 0;margin:24px 0}.summary strong{display:block;font-size:23px}tr{break-inside:avoid}.types{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.type{display:flex;align-items:center;background:white;padding:12px;gap:12px}.type img{width:70px}.type strong{display:block}footer{margin-top:30px;font-size:11px;color:#6c7b61}@media(max-width:650px){body{padding:20px 12px}.types{grid-template-columns:1fr 1fr}.type{display:block}.summary{gap:17px}td,th{padding:7px;font-size:11px}img{width:64px;height:52px}}@media print{body{background:white;padding:0;font-size:11px}thead{display:table-header-group}h1{font-size:28px}.summary{margin:15px 0}img{width:64px;height:48px}a{text-decoration:none;color:inherit}table{font-size:10px}.type{border:1px solid #eee}.no-print{display:none}}`;

function exportOfficialModel(entry, model) {
  const inventory=model.inventory;
  if (model.thumbnail?.endsWith('.png')) checkPreviewPng(resolve(output,model.thumbnail.replace(/^\//,'')));
  if(model.setNumber!==inventory.setNumber)throw new Error('Official export requires the matching inventory.');
  if(model.progressTotal!==model.steps.length)throw new Error('Build progress does not match the instruction sequence.');
  const prefix=`lego-${model.setNumber}`,title=`LEGO ${model.setNumber} — ${model.title}`;
  const csv=rows=>rows.map(row=>row.map(value=>`"${String(value??'').replaceAll('"','""')}"`).join(',')).join('\r\n');
  const used=new Map();for(const step of model.steps)for(const part of step.parts||[])used.set(part.elementId,(used.get(part.elementId)||0)+part.quantity);
  const usedQuantity=[...used.values()].reduce((sum,n)=>sum+n,0),rigidQuantity=model.steps.reduce((sum,step)=>sum+(step.partIds?.length||0),0);
  const usage={build:model.edition,usedQuantity,rigidQuantity,accessoryQuantity:usedQuantity-rigidQuantity,usedElementCount:used.size,unusedQuantity:inventory.quantityTotal-usedQuantity,note:model.details?.inventoryNote||inventory.reconciliation?.note||''};
  const rows=inventory.rows.map(row=>({...row,usedQuantity:used.get(row.elementId)||0,unusedQuantity:row.quantity-(used.get(row.elementId)||0)}));
  if(rows.some(row=>row.unusedQuantity<0))throw new Error(`Assembly exceeds printed supply in ${model.setNumber}.`);
  const sourceLinks=(model.source.booklets||[model.source]).map(book=>`<a href="${book.sourceUrl}" target="_blank" rel="noopener noreferrer">${escape(book.title||'Official instruction PDF')} ↗</a>`).join(' · ');
  const table=rows.map(row=>`<tr data-element="${row.elementId}"><th scope="row">${row.elementId}</th><td><a href="${officialPdfPage(model,row)}" target="_blank" rel="noopener noreferrer">${escape(officialBooklet(model,row).title||'Booklet')} · ${row.page}</a></td><td>${row.usedQuantity}</td><td>${row.quantity}</td></tr>`).join('');
  const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(title)} — parts inventory</title><style>${styles}tbody th{background:white}.notice{background:#f2eee2;padding:16px}.inventory-filter{display:flex;gap:12px;align-items:center;margin:20px 0}.inventory-filter input{font:inherit;padding:10px;border:1px solid #cad2c7;border-radius:6px;max-width:200px}</style></head><body><main><small>LEGO COLLECTION</small><h1>${escape(title)}</h1><p>Element IDs and quantities from the LEGO instructions, with links to the original source pages.</p><div class="summary"><div><strong>${model.pieceCount}</strong>published set pieces</div><div><strong>${usedQuantity}</strong>pieces used in this build</div><div><strong>${inventory.quantityTotal}</strong>printed inventory</div><div><strong>${rows.length}</strong>element entries</div><div><strong>${model.progressTotal}</strong>build steps</div></div><p class="notice">${escape(usage.note)}</p><p class="no-print"><a href="/?design=${entry.alias}">Open this build</a> · <a href="/${prefix}-parts.csv" download>Download inventory CSV</a> · ${sourceLinks}</p><h2>Every listed element</h2><p>Use the original booklet links to identify and compare parts.</p><label class="inventory-filter no-print">Find an element<input id="element-search" type="search" aria-label="Find a LEGO element ID"><span id="element-results" role="status">${rows.length} entries</span></label><table><thead><tr><th>LEGO element ID</th><th>Printed source</th><th>Used in build</th><th>Printed inventory</th></tr></thead><tbody>${table}</tbody><tfoot><tr><th colspan="2">Totals</th><td>${usedQuantity}</td><td>${inventory.quantityTotal}</td></tr></tfoot></table><h2>Build and display</h2><p>${escape(model.details?.instructionNote||'Follow each numbered step in the interactive build.')}</p><p>${escape(model.details?.scopeNote||'This digital prototype does not certify physical connections.')}</p><p><a href="/${prefix}-assembly.csv" download>Download step assignments</a> · <a href="/official/${model.setNumber}/model-provenance.json">3D model provenance</a></p><footer>LEGO is a trademark of the LEGO Group. Original booklets remain hosted by LEGO.</footer></main><script>const query=document.querySelector('#element-search'),rows=[...document.querySelectorAll('[data-element]')];query.addEventListener('input',()=>{let visible=0;for(const row of rows){row.hidden=!row.dataset.element.includes(query.value.trim());if(!row.hidden)visible++;}document.querySelector('#element-results').textContent=visible+' of '+rows.length+' entries';});</script></body></html>`;
  const master=[`# ${title} — parts inventory`,'',`${usedQuantity} used pieces; ${model.pieceCount} published pieces; ${inventory.quantityTotal} printed inventory items.`,'',usage.note,'','| Element ID | Used | Printed | Source |','| --- | ---: | ---: | --- |',...rows.map(row=>`| ${row.elementId} | ${row.usedQuantity} | ${row.quantity} | [Page ${row.page}](${officialPdfPage(model,row)}) |`),''].join('\n');
  const files={
    'master-list.html':html,'master-list.md':master,'inventory.json':JSON.stringify({...inventory,usage,rows},null,2),
    'parts.csv':csv([['LEGO element ID','Used in build','Printed inventory','Unused','Booklet','PDF page','Source PDF'],...rows.map(row=>[row.elementId,row.usedQuantity,row.quantity,row.unusedQuantity,row.bookletId||'',row.page,officialPdfPage(model,row)])]),
    'assembly.csv':csv([['Progress step','Step ID','Booklet','PDF pages','New rigid pieces','Total new pieces','Element quantities','3D instance IDs','Action','Existing action instance IDs'],...model.steps.map((step,index)=>[index+1,step.id,step.bookletId||'',step.pages.join(' '),step.partIds?.length||0,step.quantity??(step.parts||[]).reduce((sum,p)=>sum+p.quantity,0),(step.parts||[]).map(part=>`${part.elementId}:${part.quantity}`).join(' '),(step.partIds||[]).join(' '),step.action?.label||'',step.action?.instanceIds?.join(' ')||''])]),
    'instruction-steps.csv':csv([['Progress step','Section','Official step','Booklet','PDF pages','Official PDF'],...model.steps.map((step,index)=>[index+1,step.section,step.officialNumber??step.number,step.bookletId||'',step.pages.join(' '),officialPdfPage(model,step)])]),
  };
  for(const [suffix,contents]of Object.entries(files))writeFileSync(resolve(output,`${prefix}-${suffix}`),suffix.endsWith('.html')?portableExport(contents):contents);
  console.log(`Exported ${entry.alias}: ${model.progressTotal} steps, ${rows.length} elements, ${usedQuantity} used / ${inventory.quantityTotal} printed pieces.`);
}

for (const entry of listModels()) exportOfficialModel(entry, getModel(entry.id));
for (const name of ['sian', 'chiron', 'porsche']) copyFileSync(resolve(root, `docs/${name}-official-set.md`), resolve(output, `${name}-official-set.md`));
