import { appUrl } from './app-path.js';
import { AssemblyScene } from './assembly-scene.js';
import { officialBooklet, officialPdfPage, officialSection, officialStepTitle } from './official-source.js';

/** Official step callouts drive the interactive assembly and its saved progress. */
export function mountOfficialRoom({root,model,chapters,placed:initialPlaced,activeSet:initialSet,shell,esc,ico,iconify,bindNavigation,modal,onProgress,onReset,onDownload}) {
  const total=model.progressTotal,last=total-1,inventory=model.inventory,details=model.details||{};
  const section=step=>officialSection(model,step);
  let placed=initialPlaced,activeSet=initialSet,index=Math.min(placed,last),pageOffset=0,mode=initialPlaced===total?'model':'build',cad,disposed=false,autoTimer=null,autoRunning=false;
  const usedCounts=new Map();for(const step of model.steps)for(const part of step.parts||[])usedCounts.set(part.elementId,(usedCounts.get(part.elementId)||0)+part.quantity);
  const pageUrl=(page,item)=>officialPdfPage(model,{...item,page});
  const usedQuantity=[...usedCounts.values()].reduce((sum,n)=>sum+n,0);
  root.innerHTML=shell(`<main class="studio-main official-room"><div class="page-heading"><div><div class="eyebrow">THE COLLECTION <span class="line"></span> SET ${model.setNumber}</div><h1>${esc(model.title)}</h1><p>${esc(model.tagline||'A new addition to the collection.')}</p></div><div class="save-status" id="save-status">${ico('bookmark')}<span>Saved in this browser</span></div></div><div class="official-nav"><button class="text-button" data-nav="/">← Collection</button><span>${model.year} <span class="dot">·</span> ${esc(model.edition)} <span class="dot">·</span> Official LEGO instructions</span></div><div class="studio-grid"><section class="art-stage official-stage" aria-label="${esc(model.shortTitle||model.title)} model and instructions"><div class="official-stage-tabs" role="group" aria-label="Set viewer"><button data-mode="build" aria-pressed="false">${ico('blocks')}Build</button><button data-mode="model" aria-pressed="false">${ico('eye')}Finished preview</button><button data-mode="instructions" aria-pressed="false">${ico('layers-3')}Official instructions</button></div><div class="official-model-view" id="official-model-view"><div id="official-scene" class="official-scene"></div><div class="loading-scene" id="official-loading"><span class="spinner"></span>Assembling the preview…</div><div class="official-camera-tools" role="group" aria-label="Camera controls"><button id="official-focus">Focus next step</button><button id="official-whole">Whole build</button><button id="official-zoom-in" aria-label="Zoom in">+</button><button id="official-zoom-out" aria-label="Zoom out">−</button></div><div class="official-orbit-hint">${ico('move')}Click the gold pieces or the step marker · Drag to rotate</div><div class="official-views"><button data-view="angle" class="selected" aria-label="Angled model view">3D view</button><button data-view="side" aria-label="Side model view">Side</button><button data-view="top" aria-label="Top model view">Above</button><button data-view="front" aria-label="Front model view">Front</button></div></div><div id="official-guide" class="official-guide" hidden></div><div class="official-stage-caption" id="official-caption">Interactive assembly · Parts and quantities follow the official booklet.</div></section><aside class="build-panel official-panel" id="official-panel"></aside></div><section class="below-stage official-below"><div class="detail-note">${ico('bookmark')}<div><strong>A place for the sets you love.</strong><p>Click to place the next pieces. Progress saves automatically in this browser.</p></div></div><div class="reference-actions"><button class="text-button" id="official-parts">Parts list ${ico('blocks')}</button><button class="text-button" id="official-sources">About this build ${ico('arrow-up-right')}</button></div></section></main>`);
  bindNavigation();
  function stopAuto(){clearInterval(autoTimer);autoRunning=false;}
  function completeStep(){
    if(placed===total||mode!=='build'||!cad?.ready)return;
    const step=model.steps[placed];
    placed++;index=Math.min(placed,last);pageOffset=0;
    // Apply the completed step’s orientation before framing the next pieces.
    cad?.performAction?.(step);cad?.setProgress(placed,{animate:true});
    onProgress(placed);if(placed===total){setMode('model');return;}render();
  }
  function renderPanel(){
    const complete=placed===total,current=model.steps[Math.min(placed,last)],chapter=chapters.find(c=>placed>=c.start&&placed<c.end)||chapters.at(-1);
    const building=mode==='build'&&!complete;
    const parts=current.parts||[];
    const count=(current.partIds||[]).length;
    const action=current.action?.label|| (count?`Place ${count} ${count===1?'piece':'pieces'}`:'Join the built section');
    root.querySelector('#official-panel').innerHTML=`<div class="official-set-id"><span class="panel-eyebrow">LEGO ${model.setNumber} · ${model.year}</span><span class="official-edition">${esc(model.edition.toUpperCase())}</span></div><h2>${building?esc(chapter.title):esc(model.displayHeading||'Piece by piece.')}</h2><p class="panel-description">${building?'Click the gold pieces, the step marker or the button below. Follow each step as the pieces and assemblies come together.':esc(model.description||model.defaultDescription)}</p><div class="official-progress"><div><strong>${complete?'Your digital build is complete':`${placed} of ${total} steps built`}</strong><span>${complete?100:Math.min(99,Math.round(placed/total*100))}%</span></div><progress value="${placed}" max="${total}" aria-label="Official assembly progress"></progress></div>${complete?`<span class="finished-badge">${ico('check')} BUILD COMPLETE</span><button class="button primary" data-nav="/">Explore the collection ${ico('arrow-right')}</button><button class="button secondary" id="official-download">Save preview image ${ico('download')}</button><button class="text-button centered" id="official-reset">Build again ${ico('rotate-ccw')}</button>`:building?`<div class="official-build-step"><span>${esc(section(current).toUpperCase())} · ${esc(officialStepTitle(current).toUpperCase())}</span><strong>${esc(action)}</strong><p>${esc(current.action?.description||chapter.description)}</p></div><div class="official-up-next">${parts.map(part=>`<div><strong class="element-id">${part.elementId}</strong><span>×${part.quantity}</span></div>`).join('')}</div><button class="button primary" id="official-build-step" ${autoRunning||!cad?.ready?'disabled':''}>Build ${esc(officialStepTitle(current).toLowerCase())} ${ico('plus')}<kbd>space</kbd></button><button class="button secondary" id="official-build-chapter" ${!cad?.ready?'disabled':''}>${autoRunning?'Pause building':'Build this chapter'} ${ico(autoRunning?'pause':'fast-forward')}</button><button class="text-button centered" id="official-undo" ${placed===0||autoRunning?'disabled':''}>Undo last step ${ico('rotate-ccw')}</button>`:`<button class="button primary" id="official-start">${placed?'Continue building':'Start building'} ${ico('arrow-right')}</button>`}<div class="set-stats official-bottom-stats"><div><strong>${model.pieceCount.toLocaleString()}</strong><span>published set pieces</span></div><div><strong>${chapters.length}</strong><span>building chapters</span></div></div><div class="official-booklet-link"><button class="text-button" id="official-step-reference">View this instruction page ↗</button><a href="${officialPdfPage(model,current)}" target="_blank" rel="noopener noreferrer">Open original LEGO booklet ↗</a></div>`;
    root.querySelector('#official-start')?.addEventListener('click',()=>setMode('build'));
    root.querySelector('#official-build-step')?.addEventListener('click',completeStep);
    root.querySelector('#official-build-chapter')?.addEventListener('click',()=>{if(autoRunning){stopAuto();render();return;}const end=chapter.end;autoRunning=true;render();autoTimer=setInterval(()=>{if(placed>=end||disposed){stopAuto();render();return;}completeStep();if(placed>=end){stopAuto();render();}},500);});
    root.querySelector('#official-undo')?.addEventListener('click',()=>{if(placed>0){placed--;index=placed;cad?.setProgress(placed);onProgress(placed);render();}});
    root.querySelector('#official-step-reference')?.addEventListener('click',()=>{index=Math.min(placed,last);pageOffset=0;setMode('instructions');});
    root.querySelector('#official-download')?.addEventListener('click',onDownload);
    root.querySelector('#official-reset')?.addEventListener('click',onReset);
    bindNavigation();iconify();
  }
  function renderGuide(){
    const step=model.steps[index],page=step.pages[pageOffset],book=officialBooklet(model,step);
    root.querySelector('#official-guide').innerHTML=`<div class="official-page-heading"><span>${esc(section(step).toUpperCase())} · ${esc(officialStepTitle(step).toUpperCase())}</span><label>Jump to <select id="official-step-select" aria-label="Instruction step">${model.steps.map((s,i)=>`<option value="${i}" ${i===index?'selected':''}>${esc(section(s))} · ${esc(officialStepTitle(s))}</option>`).join('')}</select></label></div><div class="official-page-link"><h2>${esc(book.title||'Official booklet')}</h2><p>Follow ${esc(officialStepTitle(step).toLowerCase())} on page ${page} of the original LEGO instructions.</p><a class="button primary" href="${pageUrl(page,step)}" target="_blank" rel="noopener noreferrer">Open instruction page ${page} on LEGO.com ↗</a></div><div class="official-page-controls"><button id="official-prev" class="text-button" ${index===0&&pageOffset===0?'disabled':''}>← Previous</button><span>${book.title?esc(book.title)+' · ':''}Page ${page} / ${book.pageCount}${step.pages.length>1?` · ${pageOffset+1} of ${step.pages.length} for this step`:''}</span><button id="official-next" class="text-button" ${index===last&&pageOffset===step.pages.length-1?'disabled':''}>Next →</button></div><p class="official-art-credit">The original booklet opens on LEGO.com. Your build progress stays saved here.</p>`;
    root.querySelector('#official-step-select').onchange=e=>{index=Number(e.target.value);pageOffset=0;render();};
    root.querySelector('#official-prev').onclick=()=>{if(pageOffset>0)pageOffset--;else if(index>0){index--;pageOffset=model.steps[index].pages.length-1;}render();};
    root.querySelector('#official-next').onclick=()=>{if(pageOffset<step.pages.length-1)pageOffset++;else if(index<last){index++;pageOffset=0;}render();};
  }
  function setMode(next){stopAuto();mode=next;root.querySelector('#official-model-view').hidden=mode==='instructions';root.querySelector('#official-guide').hidden=mode!=='instructions';root.querySelectorAll('[data-mode]').forEach(b=>{b.classList.toggle('selected',b.dataset.mode===mode);b.setAttribute('aria-pressed',String(b.dataset.mode===mode));});root.querySelector('#official-caption').textContent=mode==='build'?'Interactive assembly · The camera follows each step · Gold marks the next pieces.':mode==='model'?(details.previewNote||'Completed assembly · Drag to inspect your build.'):'Original LEGO booklet links · Your 3D build stays saved while you browse.';root.querySelector('#official-focus').hidden=mode!=='build'||placed===total;root.querySelector('.official-orbit-hint').innerHTML=`${ico('move')}${mode==='build'&&placed<total?'Click the gold pieces or the step marker · Drag to rotate':'Drag to rotate · Scroll to zoom'}`;cad?.setPreview(mode!=='build');cad?.setProgress(placed);render();if(mode!=='instructions')cad?.resize();}
  function render(){if(disposed)return;renderPanel();if(mode==='instructions')renderGuide();}
  root.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));
  root.querySelector('#official-focus').onclick=()=>cad?.focusNext();
  root.querySelector('#official-whole').onclick=()=>cad?.showWhole();
  root.querySelector('#official-zoom-in').onclick=()=>cad?.zoomBy(.78);
  root.querySelector('#official-zoom-out').onclick=()=>cad?.zoomBy(1.28);
  root.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{cad?.setView(b.dataset.view);root.querySelectorAll('[data-view]').forEach(other=>other.classList.toggle('selected',other===b));});
  root.querySelector('#official-parts').onclick=()=>{
    const dialog=modal(`<div class="eyebrow">OFFICIAL INSTRUCTIONS · SET ${model.setNumber}</div><h2>Every piece, counted.</h2><p class="modal-description">${usedCounts.size} element entries used in this build. LEGO element IDs and quantities follow the printed inventory.</p><div class="official-inventory-note"><strong>${usedQuantity.toLocaleString()} used in this build · ${model.pieceCount.toLocaleString()} published set pieces</strong><p>${esc(details.inventoryNote||inventory.reconciliation?.note||'Quantities follow the printed inventory and numbered build steps.')}</p></div><div class="parts-actions"><a class="button secondary" href="/lego-${model.setNumber}-master-list.html" target="_blank" rel="noopener noreferrer">Full parts list ↗</a><a class="button secondary" href="/lego-${model.setNumber}-parts.csv" download>Download CSV</a></div><label class="official-search-label">Find an element<input type="search" id="official-part-search" placeholder="LEGO element ID" /></label><div class="official-parts-grid" id="official-parts-grid"></div><p class="modal-caption">Source page links open the original instructions on LEGO.com.</p>`,'parts-modal');
    const paint=query=>{const rows=inventory.rows.filter(r=>usedCounts.has(r.elementId)&&r.elementId.includes(query));dialog.querySelector('#official-parts-grid').innerHTML=rows.length?rows.map(r=>`<a class="official-part-card" href="${pageUrl(r.page,r)}" target="_blank" rel="noopener noreferrer"><strong>${r.elementId}</strong><span>Used <b>${usedCounts.get(r.elementId)}</b> · Booklet ${r.quantity}</span></a>`).join(''):'<p>No matching element IDs.</p>';};
    paint('');dialog.querySelector('#official-part-search').oninput=e=>paint(e.target.value.trim());
  };
  root.querySelector('#official-sources').onclick=()=>modal(`<div class="eyebrow">SOURCES & BUILD DETAILS</div><h2>Built around the instructions.</h2><p class="modal-description">${esc(model.title)} · LEGO ${model.setNumber} · ${model.year} · ${model.pieceCount.toLocaleString()} published pieces.</p><div class="official-source-details"><h3>Official instructions</h3><p>${esc(details.instructionNote||`${total} steps across the supplied instruction booklets.`)}</p>${(model.source.booklets||[model.source]).map(book=>`<p><a href="${book.sourceUrl}" target="_blank" rel="noopener noreferrer">${esc(book.title||'Original LEGO booklet')} ↗</a></p>`).join('')}<h3>3D assembly</h3><p>${esc(details.modelNote||'This digital model reconstructs the assembly using individual CAD parts. Each click adds the next group of pieces.')}</p><a href="/official/${model.setNumber}/model-provenance.json" target="_blank" rel="noopener noreferrer">Model provenance and part-library credits ↗</a><h3>Build scope</h3><p>${esc(details.scopeNote||'This prototype does not simulate clutch strength or certify a physical assembly. Use the original booklets when building the physical set.')}</p><p>${esc(details.attribution||'Instruction artwork © The LEGO Group. This is an independent prototype without LEGO endorsement.')}</p></div>`,'design-cost-modal');
  render();
  try {cad=new AssemblyScene(root.querySelector('#official-scene'),{model,steps:model.steps,onPlace:()=>{if(!autoRunning)completeStep();},onReady:()=>{root.querySelector('#official-loading')?.remove();cad.setProgress(placed);cad.setPreview(mode!=='build');render();},onError:()=>{const loading=root.querySelector('#official-loading');if(loading)loading.innerHTML='<p>The 3D preview could not load. Links to the official instructions are still available above.</p>';}});} catch(error){root.querySelector('#official-loading').innerHTML='<p>The 3D preview needs WebGL. You can still follow the official instructions.</p>';}
  const keyHandler=e=>{if(e.code==='Space'&&mode==='build'&&!autoRunning&&!/INPUT|TEXTAREA|SELECT|BUTTON/.test(document.activeElement.tagName)&&!document.querySelector('dialog[open]')){e.preventDefault();completeStep();}};
  document.addEventListener('keydown',keyHandler);setMode(mode);
  return {dispose(){disposed=true;stopAuto();document.removeEventListener('keydown',keyHandler);cad?.dispose();},capture(){return cad.capture();},setProgress(n){placed=n;index=Math.min(n,last);pageOffset=0;cad?.setProgress(n);if(n===0)setMode('build');else render();},setPreview(){},resetView(){cad?.setView('angle');},update(n,set){placed=n;activeSet=set;render();}};
}
