import { appUrl } from './app-path.js';
import { AssemblyScene } from './assembly-scene.js';

/** Explore licensed CAD geometry without redistributing a booklet's build sequence. */
export function mountOfficialRoom({root,model,shell,esc,ico,iconify,bindNavigation,modal,onDownload}) {
  let cad, disposed=false;
  const booklets=model.booklets.map(book=>`<a class="button secondary" href="${book.sourceUrl}" target="_blank" rel="noopener noreferrer">${esc(book.title)} ↗</a>`).join('');
  root.innerHTML=shell(`<main class="studio-main official-room"><div class="page-heading"><div><div class="eyebrow">THE COLLECTION <span class="line"></span> SET ${model.setNumber}</div><h1>${esc(model.title)}</h1><p>Community CAD model by ${esc(model.author)}.</p></div></div><div class="official-nav"><button class="text-button" data-nav="/">← Collection</button><span>LEGO® set ${model.setNumber} <span class="dot">·</span> ${model.year}</span></div><div class="studio-grid"><section class="art-stage official-stage" aria-label="${esc(model.shortTitle)} model viewer"><div class="official-model-view"><div id="official-scene" class="official-scene"></div><div class="loading-scene" id="official-loading"><span class="spinner"></span>Loading the model…</div><div class="official-camera-tools" role="group" aria-label="Camera controls"><button id="official-whole">Reset view</button><button id="official-zoom-in" aria-label="Zoom in">+</button><button id="official-zoom-out" aria-label="Zoom out">−</button></div><div class="official-orbit-hint">${ico('move')}Drag to rotate · Scroll to zoom</div><div class="official-views"><button data-view="angle" class="selected" aria-label="Angled model view">3D view</button><button data-view="side" aria-label="Side model view">Side</button><button data-view="top" aria-label="Top model view">Above</button><button data-view="front" aria-label="Front model view">Front</button></div></div><div class="official-stage-caption">Community reconstruction · Geometry and appearance may differ from the physical set.</div></section><aside class="build-panel official-panel"><div class="official-set-id"><span class="panel-eyebrow">MODEL VIEWER</span></div><h2>See every angle.</h2><p class="panel-description">${esc(model.galleryDescription)}</p><div class="set-stats"><div><strong>${model.modeledPieceCount.toLocaleString()}</strong><span>modeled pieces</span></div><div><strong>${model.pieceCount.toLocaleString()}</strong><span>published set pieces</span></div></div><p class="viewer-notice"><strong>This is a model viewer, not a build guide.</strong> Use the original LEGO® instructions for physical assembly. The viewer does not certify connections, mechanisms or safety.</p><div class="viewer-actions">${booklets}<button class="button secondary" id="official-parts">Model inventory ${ico('blocks')}</button><button class="button secondary" id="official-download" disabled>Save preview image ${ico('download')}</button><button class="text-button" id="official-sources">Credits &amp; model details ${ico('arrow-up-right')}</button></div></aside></div></main>`);
  bindNavigation();iconify();
  root.querySelector('#official-whole').onclick=()=>{cad?.setView('angle');selectView('angle');};
  root.querySelector('#official-zoom-in').onclick=()=>cad?.zoomBy(.78);
  root.querySelector('#official-zoom-out').onclick=()=>cad?.zoomBy(1.28);
  function selectView(view){root.querySelectorAll('[data-view]').forEach(button=>button.classList.toggle('selected',button.dataset.view===view));}
  root.querySelectorAll('[data-view]').forEach(button=>button.onclick=()=>{cad?.setView(button.dataset.view);selectView(button.dataset.view);});
  root.querySelector('#official-download').onclick=onDownload;
  root.querySelector('#official-sources').onclick=()=>modal(`<div class="eyebrow">MODEL SOURCES</div><h2>${esc(model.shortTitle)}</h2><div class="official-source-details"><h3>Community reconstruction</h3><p>Model by ${esc(model.author)}, under <a href="https://creativecommons.org/licenses/by/2.0/" target="_blank" rel="noopener noreferrer">CC BY 2.0 (CCAL 2.0)</a>. Part-library files retain their individual CC BY 2.0 / 4.0 notices.</p><p><a href="${model.sourceUrl}" target="_blank" rel="noopener noreferrer">Upstream community model ↗</a> · <a href="/official/${model.setNumber}/MODEL-CREDITS.md">Complete author credits and licenses</a></p><p><a href="/official/${model.setNumber}/model-provenance.json">Documented adaptations and source hashes</a></p><h3>Scope</h3><p>${esc(model.scope)}</p><p>The public viewer does not reproduce the booklets’ full instruction sequences or callouts. Original booklets open on LEGO.com.</p><h3>Data and software</h3><p>Catalog crosswalk data is from <a href="https://rebrickable.com/downloads/" target="_blank" rel="noopener noreferrer">Rebrickable Downloads</a>. The model inventory is counted from the attributed CAD instances.</p><p><a href="/about.html">Privacy, third-party notices and collection credits</a></p></div>`,'design-cost-modal');
  root.querySelector('#official-parts').onclick=async()=>{
    const dialog=modal(`<div class="eyebrow">COMMUNITY CAD INVENTORY</div><h2>The pieces in this model.</h2><p class="modal-description">Counts describe the digital reconstruction, not a complete box inventory or buying list. LDraw filenames and color codes retain the model’s attribution.</p><div class="parts-actions"><a class="button secondary" href="/model-${model.setNumber}-inventory.csv" download>Download model CSV</a><a class="button secondary" href="/official/${model.setNumber}/MODEL-CREDITS.md">Model credits</a></div><label class="official-search-label">Find an LDraw part<input type="search" id="official-part-search" placeholder="Part filename" /></label><div id="official-inventory-results" role="status">Loading the model inventory…</div><div id="official-parts-grid" class="official-parts-grid"></div>`,'parts-modal');
    try {
      const response=await fetch(appUrl(`/official/${model.setNumber}/model-inventory.json`));
      if(!response.ok)throw new Error('Inventory unavailable');
      const rows=await response.json();
      if(disposed||!dialog.open)return;
      const paint=query=>{const visible=rows.filter(row=>row.partFile.toLowerCase().includes(query.toLowerCase()));dialog.querySelector('#official-inventory-results').textContent=`${visible.length} of ${rows.length} part and color entries`;dialog.querySelector('#official-parts-grid').innerHTML=visible.map(row=>`<div class="official-part-card"><strong>${esc(row.partFile)}</strong><span>LDraw color ${row.ldrawColor} · Quantity ${row.quantity}</span></div>`).join('');};
      paint('');dialog.querySelector('#official-part-search').oninput=e=>paint(e.target.value.trim());
    }catch{dialog.querySelector('#official-inventory-results').textContent='The inventory could not load. Please try again.';}
  };
  try{cad=new AssemblyScene(root.querySelector('#official-scene'),{model,steps:[],onReady:()=>{root.querySelector('#official-loading')?.remove();cad.setPreview(true);root.querySelector('#official-download').disabled=false;},onError:()=>{const loading=root.querySelector('#official-loading');if(loading)loading.innerHTML='<p>The 3D model could not load. The original instruction links remain available.</p>';}});}catch{root.querySelector('#official-loading').innerHTML='<p>The model viewer needs WebGL. The original instruction links remain available.</p>';}
  return {dispose(){disposed=true;cad?.dispose();},capture(){return cad.capture();}};
}
